### ISSUE TITLE
Allow changing the `Q` for shelf filters

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api-v2#64]
This is something that most profesionnal audio software on my system can do, we should have a look to see if we can make it work with the current equations.

**Comment by rtoy** [comment]
This will take some work to see if we can do something and still preserve backward compatibility.  Not sure that's possible since the default value of Q that wasn't used before but will be used now will probably not give the same filter responses.  Have to do the analysis to see.

For reference, I'm using https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html and looking at eqns 5-7, and 10 and the filter formulas for the peaking, lowshelf, and highshelf filters.

**Comment by svgeesus** [comment]
Dup of https://github.com/WebAudio/web-audio-api-v2/issues/67
